DY:
  name: "DY"
  color: "kAzure+7"
  sub_processes:
    - DY_M_10to50
    - DYto2E_M_50
    - DYto2Mu_M_50
    - DYto2Tau_M_50

DYto2L_InclusivePlusBinned:
  processors: *DY_processors_allFlavors
  corrections:
    Vpt:
      type: DY
      stages: [ 'AnalysisCache', 'HistTuple' ]
  datasets: [ ]

DY_M_10to50:
  name: "DY M10to50"
  color: "kAzure+10"
  datasets: [ ]

DYto2E_M_50:
  processors: *DY_processors
  datasets: [ ]

DYto2Mu_M_50:
  processors: *DY_processors
  datasets: [ ]

DYto2Tau_M_50:
  processors: *DY_processors
  datasets: [ ]

DY_LO:
  datasets: [ ]

TT:
  name: "t#bar{t}"
  color: "kGreen-3"  # eliminates need for plot.yaml
  datasets: [ ]

ST:
  name: "ST"
  color: "kPink+1"
  datasets: [ ]

DY_LowMass:
  name: "DY M10to50"
  color: "kAzure+10"
  datasets: [ ]

DY_HighMass:
  name: "DY M50"
  color: "kAzure+7"
  datasets: [ ]

W:
  name: "W"
  color: "kGreen"  # eliminates need for plot.yaml
  datasets: [ ]

VV:
  name: "VV"
  color: "kGreen+2"  # eliminates need for inputs.yaml
  datasets: [ ]

SingleHiggs:
  name: "Single Higgs"
  color: "kRed"
  datasets: [ ]

XtoHHto2B2W_DoubleLepton:
  name: "XtoHHto2B2W_DoubleLepton"
  color: "kBlack"
  is_meta_process: true
  meta_setup:
    dataset_name_pattern: XtoYHto2B2Wto2B2L2Nu_MX_(\d+)_MY_125
    parameters: [ MASS ]
    process_name: XtoHHto2B2W_2L_${MASS}
    name_pattern: Xto2B2W 2L ${MASS} GeV (x50)
    to_plot:
      - [ '300' ]
      - [ '600' ]
      - [ '1000' ]
    plot_color: [ "kBlack", "kBlue", "kRed" ]
    channels: [ "eE", "eMu", "muMu" ]
  datasets: [ ]


XtoHHto2B2W_SingleLepton:
  name: "XtoHHto2B2W_SingleLepton"
  color: "kBlack"
  is_meta_process: true
  meta_setup:
    dataset_name_pattern: XtoYHto2B2Wto2B2Q1L1Nu_MX_(\d+)_MY_125
    parameters: [ MASS ]
    process_name: XtoHHto2B2W_1L_${MASS}
    name_pattern: Xto2B2W 1L ${MASS} GeV (x50)
    to_plot:
      - [ '300' ]
      - [ '600' ]
      - [ '1000' ]
    plot_color: [ "kBlack", "kBlue", "kRed" ]
    channels: [ "e", "mu" ]
  datasets: [ ]

Data_Full:
  name: "Data"
  datasets: [ ]

custom_CI:
  name: "custom for CI and test purposes"
  color: "kAzure+10"
  datasets:
    - custom_CI
