Run3_Model:
  name: "Base model for Run 3"
  backgrounds:
    - TT
    - DY
    - ST
    - VV
    - W
    - SingleHiggs
    # - QCD_PT
  signals:
    - XtoHHto2B2W_SingleLepton
    - XtoHHto2B2W_DoubleLepton
  data:
    - Data_Full

OnlyData:
  name: "Only Data"
  backgrounds: [ ]
  signals: [ ]
  data:
    - Data_Full

TestModel:
  name: "Test model for CI"
  backgrounds:
    - custom_CI_Background
  signals: # WARNING: for 2024 no signal sample available, using a file from bbtt signals..
    - custom_CI_Signal
  data:
    - custom_CI_Data

Production_Model:
  name: "Model for anatuple production"
  backgrounds:
    - TT
    - DY
    - ST
    - VV
    # - VV_inclusive
    - W
    - DY_LO
    - SingleHiggs
  signals:
    - XtoHHto2B2W_SingleLepton
    - XtoHHto2B2W_DoubleLepton
    - GluGluToRadion_DoubleLepton
    - GluGluToRadion_SingleLepton
    - GluGluToBulkGraviton_DoubleLepton
    - GluGluToBulkGraviton_SingleLepton
  data:
    - Data_Full
